//! The protected locations the application can be denied, and the purpose strings macOS shows for
//! them, are one list with two consumers (feature 028, FR-027).
//!
//! `micold-core::permission_failure` classifies a denied file access into a `ProtectedLocation` so
//! the client can say *which* permission is missing. macOS only ever offers to grant a permission
//! it has a `NS*UsageDescription` string for. A location classified without a matching string
//! therefore produces the worst possible message: it tells the user to grant something the system
//! will never ask about.
//!
//! The list itself comes from the contract (`specs/028-macos-package/data-model.md` §2), which is
//! why it is written out here rather than derived from either consumer — a list derived from one
//! side cannot catch that side drifting.

use std::fs;
use std::path::{Path, PathBuf};

/// The protected locations of data-model.md §2, each with the key macOS reads for it.
///
/// Adding a variant to `ProtectedLocation` means adding a row here, which means adding the key to
/// the plist. That is the whole point: the failure lands at the row, not at a user's prompt.
const LOCATIONS: &[(&str, &str)] = &[
    ("Documents", "NSDocumentsFolderUsageDescription"),
    ("Desktop", "NSDesktopFolderUsageDescription"),
    ("Downloads", "NSDownloadsFolderUsageDescription"),
    ("RemovableVolume", "NSRemovableVolumesUsageDescription"),
    ("NetworkVolume", "NSNetworkVolumesUsageDescription"),
];

fn repo_root() -> PathBuf {
    // tests/ -> micold-core/ -> crates/ -> repo root
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn plist_path() -> PathBuf {
    repo_root().join("packaging/macos/Info.plist.in")
}

fn plist() -> String {
    let path = plist_path();
    fs::read_to_string(&path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()))
}

/// The value of a `<key>` in a plist, as text. `None` when the key is absent.
///
/// A plist is `<key>K</key><string>V</string>`; the value is whatever sits between the first `>`
/// and the next `<` after the key. Text is enough here — the file is generated by nobody and
/// hand-edited by us, and `plutil -lint` in `scripts/macos-bundle.sh` is what checks it is
/// well-formed.
fn string_value(source: &str, key: &str) -> Option<String> {
    let needle = format!("<key>{key}</key>");
    let after = source.split_once(&needle)?.1;
    let open = after.find("<string>")?;
    // Anything before the opening `<string>` other than whitespace means this key holds a
    // different type, and the caller asked for a string.
    if !after[..open].trim().is_empty() {
        return None;
    }
    let rest = &after[open + "<string>".len()..];
    let close = rest.find("</string>")?;
    Some(rest[..close].to_string())
}

#[test]
fn every_protected_location_has_a_usage_description() {
    let source = plist();
    let mut missing = Vec::new();
    for (location, key) in LOCATIONS {
        match string_value(&source, key) {
            Some(value) if !value.trim().is_empty() => {}
            Some(_) => missing.push(format!("{location}: {key} is empty")),
            None => missing.push(format!("{location}: {key} is absent")),
        }
    }
    assert!(
        missing.is_empty(),
        "{} declares no usable purpose string for:\n  {}\n\
         macOS shows this text inside its own permission prompt. Without it the user is asked to \
         grant access to their files with no reason given, and a location the application can \
         classify but the system never prompts for cannot be granted at all.",
        plist_path().display(),
        missing.join("\n  "),
    );
}

#[test]
fn a_purpose_string_says_something() {
    let source = plist();
    let mut terse = Vec::new();
    for (location, key) in LOCATIONS {
        let Some(value) = string_value(&source, key) else {
            continue; // the test above owns absence
        };
        // A prompt is read in one breath by someone deciding whether to trust the app. A key
        // echoing its own name, or a handful of characters, is not an explanation.
        if value.trim().len() < 20 || value.contains("UsageDescription") {
            terse.push(format!("{location}: {key} = {value:?}"));
        }
    }
    assert!(
        terse.is_empty(),
        "these purpose strings do not explain anything to the user:\n  {}",
        terse.join("\n  "),
    );
}

/// The scan itself, against inputs whose verdict is known — so a rewrite of `string_value` that
/// happens to report everything present cannot pass the tests above.
#[test]
fn the_scan_notices_an_absent_or_empty_key() {
    let present = "<key>NSDesktopFolderUsageDescription</key><string>Because.</string>";
    assert_eq!(
        string_value(present, "NSDesktopFolderUsageDescription").as_deref(),
        Some("Because."),
    );
    assert_eq!(
        string_value(present, "NSDocumentsFolderUsageDescription"),
        None
    );
    assert_eq!(
        string_value(
            "<key>NSDesktopFolderUsageDescription</key><string></string>",
            "NSDesktopFolderUsageDescription",
        )
        .as_deref(),
        Some(""),
    );
    // A key of a non-string type is not a purpose string, whatever follows it.
    assert_eq!(
        string_value(
            "<key>NSDesktopFolderUsageDescription</key><true/><string>elsewhere</string>",
            "NSDesktopFolderUsageDescription",
        ),
        None,
    );
}
