//! T013 — the schema-hash guard guards itself (contracts/protocol.md §4, Decision 4).
//!
//! `SCHEMA_HASH` is baked by `build.rs` from the canonical text of the protocol source. These tests
//! prove (a) it is real (non-zero and wired to the actual files), and (b) it is *sensitive*: editing
//! a message struct changes it, and a version-only bump changes the handshake tuple even when the
//! hash does not. Both use the same `hashing` functions the build script uses, so there is exactly
//! one implementation under test.
//!
//! # Feature 027 moved the hash, once, deliberately
//!
//! `ClientMsg::Hello` gained the authentication token and the build fingerprint, and
//! `RefusalReason` gained `AuthRejected` and `StaleDevImage` — so `SCHEMA_HASH` changed and
//! `PROTOCOL_VERSION` went 5 → 6 with it. Nothing here pins the hash to a literal, so these tests
//! stay green across that move by construction; the assertion that the move was *intended* is the
//! version bump beside it, which `a_version_only_bump_changes_the_handshake_tuple` covers.

use std::fs;
use std::path::Path;

use micold_core::protocol::hashing::{canonicalize, schema_hash};
use micold_core::protocol::version::{PROTOCOL_VERSION, SCHEMA_HASH};

fn read_protocol_source() -> (String, String, String) {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("src")
        .join("protocol");
    let messages = fs::read_to_string(dir.join("messages.rs")).expect("messages.rs");
    let grid = fs::read_to_string(dir.join("grid.rs")).expect("grid.rs");
    let envelope = fs::read_to_string(dir.join("envelope.rs")).expect("envelope.rs");
    (messages, grid, envelope)
}

#[test]
fn schema_hash_is_non_trivial() {
    assert_ne!(SCHEMA_HASH, [0u8; 32], "SCHEMA_HASH must not be all-zero");
}

#[test]
fn baked_hash_matches_a_recompute_over_the_real_source() {
    let (messages, grid, envelope) = read_protocol_source();
    let recomputed = schema_hash(&messages, &grid, &envelope);
    assert_eq!(
        recomputed, SCHEMA_HASH,
        "build.rs must hash the same protocol source these tests read; \
         if this fails the generator and the crate have drifted"
    );
}

#[test]
fn editing_a_message_struct_changes_the_hash() {
    let (messages, grid, envelope) = read_protocol_source();
    let baseline = schema_hash(&messages, &grid, &envelope);

    // Simulate a wire-visible edit: a new field on an existing message.
    let mutated = messages.replace(
        "pub enum ClientMsg {",
        "pub enum ClientMsg {\n    NewlyAddedVariant { extra: u64 },",
    );
    assert_ne!(
        mutated, messages,
        "the anchor text must exist to be mutated"
    );

    let after = schema_hash(&mutated, &grid, &envelope);
    assert_ne!(
        after, baseline,
        "a struct/enum edit MUST change SCHEMA_HASH — that is the whole guard"
    );
}

#[test]
fn a_comment_only_edit_does_not_churn_the_hash() {
    let (messages, grid, envelope) = read_protocol_source();
    let baseline = schema_hash(&messages, &grid, &envelope);

    // Prepend a fresh full-line comment: canonicalisation drops it, so the hash is stable.
    let commented = format!("// a brand new doc note that changes nothing on the wire\n{messages}");
    let after = schema_hash(&commented, &grid, &envelope);
    assert_eq!(
        after, baseline,
        "a comment-only edit must not change the hash (canonicalisation drops comment lines)"
    );
}

#[test]
fn a_version_only_bump_changes_the_handshake_tuple() {
    // The hash can be identical across a version bump (no struct changed), but the handshake tuple
    // (version, hash) must still differ so a version-only change is caught.
    let before = (PROTOCOL_VERSION, SCHEMA_HASH);
    let after = (PROTOCOL_VERSION + 1, SCHEMA_HASH);
    assert_ne!(
        before, after,
        "the (version, hash) handshake tuple must change on a version bump"
    );
}

#[test]
fn canonicalize_ignores_blank_and_comment_lines_only() {
    let src = "// comment\n\n   \npub struct A;  \n    // indented comment\npub struct B;\n";
    assert_eq!(canonicalize(src), "pub struct A;\npub struct B;\n");
}

// -------------------------------------------------------------------------------------------
// The build fingerprint (feature 027, research R8)
// -------------------------------------------------------------------------------------------

#[test]
fn the_build_fingerprint_is_a_separate_mechanism_from_the_schema_hash() {
    use micold_core::protocol::version::BUILD_FINGERPRINT;

    // Both are generated by `build.rs`, and it would be easy to assume one subsumes the other. It
    // does not: `SCHEMA_HASH` covers three protocol files and answers "do we agree about the
    // wire?", while the fingerprint covers this crate's whole source tree and answers "were we
    // built from the same thing?". A change to `settings.rs` moves the second and not the first,
    // and that gap is exactly what a stale `:dev` image falls into.
    assert!(!BUILD_FINGERPRINT.is_empty());
    assert!(BUILD_FINGERPRINT.chars().all(|c| c.is_ascii_hexdigit()));

    let hash_hex: String = SCHEMA_HASH.iter().map(|b| format!("{b:02x}")).collect();
    assert!(
        !hash_hex.starts_with(BUILD_FINGERPRINT),
        "the fingerprint must not be a prefix of the schema hash — that would mean one is \
         derived from the other and the gap above is not covered"
    );
}

// ---------------------------------------------------------------------------------------
// Feature 026 — one hash move for the whole feature (T020)
// ---------------------------------------------------------------------------------------

/// The protocol version feature 026 bumped to.
///
/// Pinned, not read from a constant, because that is what makes this a gate rather than a mirror.
/// Feature 026 makes **five** wire changes — `provider` on `ClientMsg::SessionCreate` and on
/// `SessionSummary`, and `default_ai_cli` on `DaemonSettings`, `SettingsSet` and `SettingsChanged`
/// — and the whole point of doing them in one edit is that the hash moves **once**. A second bump
/// later in the feature, when US3 comes to consume the outbound field, fails here.
///
/// It read 6 while this branch was based on a `main` at 5. Rebasing onto a `main` that had since
/// bumped 5 → 6 for `SessionSummary::live_shells` (feature 012, BUG-003) moved this feature's one
/// bump up to 7 — which is exactly the "another feature's bump" case the assertion below names,
/// and the constant follows it rather than the feature bumping twice.
///
/// It moved again, 7 → 8, when feature 027 merged: 027 had developed against 6 and 7 of its own
/// while 026 was taking those same numbers here, so the merged wire carries both features'
/// changes and both cannot be 7. Same case, same answer — the constant follows the bump, and 026
/// still costs exactly one.
///
/// And 8 → 9 for `010` BUG-022, which makes a client *window* nameable on the wire
/// (`ClientMsg::Hello::client_instance`, and a `ClientIdentity` on `DaemonMsg::Displaced::by` and
/// `RefusalReason::ProjectBusy::holder`). Third time, same case, same answer.
///
/// And 9 → 10 for feature 029's `ClientMsg::WorktreeRefresh`. Fourth time, same case, same answer:
/// the constant follows the wire, and 026 still costs exactly one bump. That this line has now been
/// written four times is the gate working — each of those features had to come here and say which
/// bump was theirs.
///
/// And 10 → 11 for feature 029's Pi provider (`AiCli::Pi`, and `pi_activity_component` on
/// `DaemonSettings` and `SettingsSet`), which had developed against the 10 `WorktreeRefresh` took.
/// Fifth time, same case, same answer.
///
/// And 11 → 12 for `002` BUG-003's `ClientMsg::ProjectActivate`. Sixth time, same case, same answer.
///
/// And 12 → 13 for `006` BUG-007's `ClientMsg::TerminalColorScheme`. Seventh time, same case, same
/// answer.
///
/// And 13 → 14 for feature 032's `SessionLabel::Derived`, which `SessionSummary.title` carries.
/// Eighth time, same case, same answer — with one difference worth writing down: `SessionLabel`
/// lives in `session.rs`, which `SCHEMA_HASH` does **not** cover (it hashes the protocol sources
/// only), so the hash did not move and nothing but this pin forced the bump (032 research R3).
///
/// And 14 → 15 for `029` BUG-001's `cwd` on `ClientMsg::AiCliAvailabilityRequest`, which had
/// developed against the 13 that feature 032's label took to 14. Ninth time, same case, same
/// answer.
///
/// And 15 → 16 for feature 034's `ClientMsg::RemoteList` / `OperationResult::RemoteList`, which
/// let the client ask for a project's own remote URLs. Tenth time, same case, same answer.
///
/// And 16 → 17 for feature 034's `tool_server_enabled` on `DaemonSettings` and `SettingsSet`
/// (FR-004). Eleventh time, same case, same answer.
///
/// And 17 → 18 for feature 034's confirmations (`DaemonMsg::ConfirmationRequested` /
/// `ConfirmationWithdrawn`, `ClientMsg::ConfirmationAnswer`, FR-014). Twelfth time, same case, same
/// answer.
///
/// And 18 → 19 for feature 034's `cross_session_access` on `DaemonSettings` and `SettingsSet`
/// (FR-016). Thirteenth time, same case, same answer.
///
/// And 19 → 20 for feature 037's `env` on `DaemonMsg::AiCliAvailability`: the state of the
/// environment the answer was walked in, which had developed against the 17 that feature 034
/// took to 18 and then 19. Fourteenth time, same case, same answer.
///
/// And 20 → 21 for feature 039's `ClientMsg::WindowView` and `SessionSummary::attention_seq`: a
/// window reports the session it has in view, and every session carries its count of attention
/// events. Fifteenth time, same case, same answer.
///
/// And 21 → 22 for feature 040's `ClientMsg::MergedBranchCheck` /
/// `OperationResult::MergedBranchCheck` and `pr_status_enabled` on `DaemonSettings` and
/// `SettingsSet`: one bump for both, taking 22 as
/// feature 039 took 21. Sixteenth time, same case, same answer.
///
/// And 22 → 23 for feature 039's `ClientMsg::AttentionClaim` and `DaemonMsg::AttentionGranted`: a
/// window claims an attention event and the service grants each one once. Seventeenth time, same
/// case, same answer.
///
/// And 23 → 24 for feature 039's `SessionSummary::unread`: every session carries whether it is
/// unread. Eighteenth time, same case, same answer.
///
/// And 24 → 25 for feature 039's `ClientMsg::SessionReveal` and `DaemonMsg::RevealSession`: a
/// click on a notification is sent to the service, which forwards it to one window. Nineteenth
/// time, same case, same answer.
///
/// And 25 → 26 for feature 039's `activation` on both reveal messages: the Wayland activation
/// token of the click rides with the reveal. Twentieth time, same case, same answer.
/// And 26 → 27 for feature 039's `desktop_notifications` on `DaemonSettings` and `SettingsSet`
/// (contract W4): the service holds the Desktop notifications switch for every window. Twenty-first
/// time, same case, same answer.
///
/// And 27 → 28 for feature 582's attach messages (`AttachDiscover`, `AttachApply`, `AttachReport`,
/// `OperationResult::AttachApplied`): new variants an older peer cannot decode.
///
/// And 28 → 29 for feature 010 BUG-592's `DaemonMsg::ShellOpenFailed`: a refused shell open is
/// reported to the client that asked. A new variant an older client cannot decode.
///
/// And 29 → 30 for feature 011 BUG-442's `ClientMsg::SessionRestart`: the AI CLI's manual restart
/// re-sources the session's directory first. A new variant an older service cannot decode.
///
/// And 30 → 31 for feature 613's `kind` on `DaemonMsg::AttentionGranted` (wire W5.1): the grant
/// says which kind of event the window notifies for. An older peer would fail to decode it.
///
/// And 31 → 32 for feature 613's `DaemonMsg::SessionErrorNotice` (wire W5.2): the service tells
/// one window that a session ended because of an error. A new variant an older client cannot
/// decode.
///
/// And 32 → 33 for feature 613's `notification_kinds` and `long_task_threshold_secs` on
/// `DaemonSettings` and `SettingsSet` (wire W5.3, W5.4, W5.6): the service holds the per-kind
/// switches and the long-task threshold for every window. An older peer cannot decode them.
const FEATURE_026_PROTOCOL_VERSION: u32 = 33;

#[test]
fn the_wire_changes_for_this_feature_cost_exactly_one_version_bump() {
    assert_eq!(
        PROTOCOL_VERSION, FEATURE_026_PROTOCOL_VERSION,
        "the protocol version moved. If that is another feature's bump, update this constant \
         along with the rest of that feature's wire change. If it is feature 026 bumping a second \
         time, it should not be: US3 consumes `SessionSummary::provider`, which T029 already put \
         on the wire, and consuming a field is not a wire change"
    );
}

#[test]
fn every_field_this_feature_added_is_present_in_one_protocol_source() {
    // The other half of "one bump": the bump has to *cover* all five. A version that moved while
    // one of the additions was still to come would satisfy the test above and still cost a second
    // move later.
    //
    // Read from the source text rather than from the types, deliberately — this file's whole
    // subject is the text `build.rs` hashes, and a field added to a *different* file would not
    // change the hash however correct the type looked.
    let (messages, _grid, _envelope) = read_protocol_source();
    for anchor in [
        // Inbound: the client's resolved choice.
        "SessionCreate {",
        // Outbound: the label a row reads (FR-016).
        "pub provider: AiCli,",
        // The service-owned preference, in all three of its shapes.
        "pub default_ai_cli: AiCli,",
        "default_ai_cli: Option<AiCli>,",
    ] {
        assert!(
            messages.contains(anchor),
            "`{anchor}` is not in messages.rs — feature 026's wire change is incomplete, so the \
             single bump this feature is allowed does not yet cover all of it"
        );
    }
    assert_eq!(
        canonicalize(&messages).matches("provider: AiCli,").count(),
        2,
        "exactly two `provider: AiCli` fields ride the wire: one inbound on `SessionCreate`, one \
         outbound on `SessionSummary`"
    );
}

#[test]
fn the_availability_answer_carries_the_environment_state_in_the_hashed_source() {
    // Feature 037, contract A1. Read from the text `build.rs` hashes, as above: the field has to
    // sit in `messages.rs` for the schema hash to be the one of the message set that has it.
    let (messages, _grid, _envelope) = read_protocol_source();
    assert!(
        canonicalize(&messages).contains("env: Option<SpawnEnv>,"),
        "`DaemonMsg::AiCliAvailability` does not carry `env: Option<SpawnEnv>` in messages.rs, \
         so version 20's hash is not the hash of the answer that says why a CLI is missing"
    );
}

#[test]
fn the_view_report_and_the_attention_sequence_are_in_the_hashed_source() {
    // Feature 039, contract W1 (version 21). Read from the text `build.rs` hashes, as above.
    let (messages, _grid, _envelope) = read_protocol_source();
    let messages = canonicalize(&messages);
    for anchor in [
        // Inbound: what the window has in view.
        "WindowView {",
        "in_view: Option<SessionId>,",
        // Outbound: the session's count of attention events.
        "pub attention_seq: u64,",
    ] {
        assert!(
            messages.contains(anchor),
            "`{anchor}` is not in messages.rs, so version 21's hash is not the hash of the \
             message set that reports views and counts attention events"
        );
    }
}

// ---------------------------------------------------------------------------------------
// Feature 040 — one bump for the merged-branch question and the pull request switch
// ---------------------------------------------------------------------------------------

/// U58 (feature 040, contracts/reading-and-wire.md §5). The merged-branch question and the pull
/// request switch ship together, so they cost one version: 22, the next free number after
/// feature 039 took 21. Both are read from the text `build.rs` hashes, as above, so that 22's
/// hash is the hash of the message set that has all of it.
#[test]
fn the_merged_branch_question_and_the_pull_request_switch_cost_one_bump_to_22() {
    // The number itself is pinned once, by `FEATURE_026_PROTOCOL_VERSION` above: later features
    // take later numbers (039 took 23), so this test checks only what version 22 added.
    let (messages, _grid, _envelope) = read_protocol_source();
    let hashed = canonicalize(&messages);
    for anchor in [
        "pub struct MergedBranchQuery {",
        "pub enum BranchContainment {",
        "checks: Vec<MergedBranchQuery>,",
        "answers: Vec<BranchContainment>,",
        "pr_status_enabled: Option<bool>,",
        "pub pr_status_enabled: bool,",
    ] {
        assert!(
            hashed.contains(anchor),
            "`{anchor}` is not in messages.rs, so version 22's hash does not cover all of \
             feature 040's wire change"
        );
    }
}

#[test]
fn the_claim_and_the_grant_are_in_the_hashed_source() {
    // Feature 039, contract W1 (version 23). U13. Read from the text `build.rs` hashes, as above.
    let (messages, _grid, _envelope) = read_protocol_source();
    let messages = canonicalize(&messages);
    for anchor in ["AttentionClaim {", "AttentionGranted {"] {
        assert!(
            messages.contains(anchor),
            "`{anchor}` is not in messages.rs, so version 23's hash is not the hash of the \
             message set that claims and grants attention events"
        );
    }
}

#[test]
fn the_grants_kind_is_in_the_hashed_source() {
    // Feature 613, wire W5.1 (version 31). Read from the text `build.rs` hashes, as above.
    let (messages, _grid, _envelope) = read_protocol_source();
    assert!(
        canonicalize(&messages).contains("kind: NotificationKind,"),
        "`kind: NotificationKind,` is not in messages.rs, so version 31's hash is not the hash of \
         the message set whose grant carries the notification kind"
    );
}

#[test]
fn the_session_error_notice_is_in_the_hashed_source() {
    // Feature 613, wire W5.2 (version 32). Read from the text `build.rs` hashes, as above.
    let (messages, _grid, _envelope) = read_protocol_source();
    assert!(
        canonicalize(&messages).contains("SessionErrorNotice {"),
        "`SessionErrorNotice {{` is not in messages.rs, so version 32's hash is not the hash of \
         the message set that tells a window a session ended with an error"
    );
}

#[test]
fn unread_is_in_the_hashed_source() {
    // Feature 039, contract W2 (version 24). U14. Read from the text `build.rs` hashes, as above.
    let (messages, _grid, _envelope) = read_protocol_source();
    assert!(
        canonicalize(&messages).contains("pub unread: bool,"),
        "`pub unread: bool,` is not in messages.rs, so the hash is not the hash of the message \
         set that carries unread state"
    );
}

#[test]
fn the_reveal_and_its_forward_are_in_the_hashed_source() {
    // Feature 039, contract W3 (version 25). U15. Read from the text `build.rs` hashes, as above.
    let (messages, _grid, _envelope) = read_protocol_source();
    let messages = canonicalize(&messages);
    for anchor in ["SessionReveal {", "RevealSession {"] {
        assert!(
            messages.contains(anchor),
            "`{anchor}` is not in messages.rs, so the hash is not the hash of the message set \
             that asks for a session to be revealed and forwards the request"
        );
    }
}

#[test]
fn the_activation_token_is_in_the_hashed_source_of_both_reveal_messages() {
    // Feature 039, contract W3.4 (version 26). U16. Read from the text `build.rs` hashes.
    let (messages, _grid, _envelope) = read_protocol_source();
    let messages = canonicalize(&messages);
    for message in ["SessionReveal {", "RevealSession {"] {
        let body = &messages[messages
            .find(message)
            .expect("the message is in messages.rs")..];
        let body = &body[..body.find('}').expect("the message body closes")];
        assert!(
            body.contains("activation: Option<String>"),
            "`{message}` has no `activation: Option<String>`, so the hash is not the hash of the \
             message set that carries the activation token"
        );
    }
}

#[test]
fn the_desktop_notifications_setting_is_in_the_hashed_source() {
    // Feature 039, contract W4. U17. Read from the text `build.rs` hashes, as above.
    let (messages, _grid, _envelope) = read_protocol_source();
    let messages = canonicalize(&messages);
    for anchor in [
        // Outbound: the value every window follows.
        "pub desktop_notifications: bool,",
        // Inbound: `None` leaves it unchanged.
        "desktop_notifications: Option<bool>,",
    ] {
        assert!(
            messages.contains(anchor),
            "`{anchor}` is not in messages.rs, so the hash is not the hash of the message set \
             that carries the Desktop notifications setting"
        );
    }
}

#[test]
fn the_notification_kinds_and_the_threshold_are_in_the_hashed_source() {
    // Feature 613, wire W5.3, W5.4, W5.6 (version 33). Read from the text `build.rs` hashes.
    let (messages, _grid, _envelope) = read_protocol_source();
    let messages = canonicalize(&messages);
    for anchor in [
        // Outbound: the values every window follows.
        "pub notification_kinds: NotificationKinds,",
        "pub long_task_threshold_secs: u64,",
        // Inbound: `None` leaves each unchanged.
        "notification_kinds: Option<NotificationKinds>,",
        "long_task_threshold_secs: Option<u64>,",
    ] {
        assert!(
            messages.contains(anchor),
            "`{anchor}` is not in messages.rs, so version 33's hash is not the hash of the \
             message set that carries the kind switches and the long-task threshold"
        );
    }
    assert_eq!(
        micold_core::protocol::version::PROTOCOL_VERSION,
        33,
        "W5.3, W5.4 and W5.6 are version 33"
    );
}
