//! The design tokens as a CSS custom-property sheet (feature 028 — FR-030, SC-014).
//!
//! The published documentation site is dressed in the application's own design tokens rather than
//! in a copy of them. A copy would be a second source of truth that drifts the first time a colour
//! moves, and drift here is not cosmetic: every screenshot on the site is taken from the running
//! application, so a site whose surfaces have gone stale frames a picture of the real ones.
//!
//! So this module is the one place the tokens become CSS, and it is a **pure function** — token set
//! in, stylesheet text out. It reads no environment, touches no file and makes no decision about
//! where the sheet is written; `src/bin/micold-tokens-css.rs` prints what it returns. That is what
//! lets the whole contract in `specs/028-docs-site-github-pages/contracts/theme-variables.md` be
//! asserted by unit tests in this file rather than by inspecting a build product.
//!
//! Two things are deliberately *not* emitted:
//!
//! - **`tracking`.** The type scale records Material's letter-spacing but the renderer never applies
//!   it (FR-042). Emitting it would let the site set a spacing no screenshot on the site can show.
//! - **Component anatomy and density.** Sizes for buttons, chips and list rows describe controls the
//!   documentation does not have (FR-029b). The site borrows the application's *look*, not its
//!   widgets.

use super::{ColorScheme, Rgb, Roles, elevation, motion, roles, shape, spacing, state, typography};
use std::fmt::Write as _;

/// The header every generated sheet opens with. Someone will open this file in an editor; the first
/// line is the only warning they get before they change something a build overwrites.
const HEADER: &str =
    "/* GENERATED by micold-tokens-css from crates/micold-core/src/tokens/. Do not edit. */";

/// The complete stylesheet: the header comment, the light block, and the dark block.
///
/// Every name is emitted in both blocks. Scheme-independent tokens — the type scale, corner radii,
/// durations, state opacities — are therefore repeated with identical values rather than hoisted
/// into the light block and inherited. That is deliberate: a reader (and the test) can then check
/// one property, "both blocks define the same names", instead of reasoning about which subset the
/// dark block is entitled to omit. A missing name does not fail loudly in CSS; it falls back to an
/// initial value and the page quietly renders in something that is not the application's palette.
pub fn stylesheet() -> String {
    let mut out = String::with_capacity(8 * 1024);
    out.push_str(HEADER);
    out.push('\n');
    block(&mut out, ":root", ColorScheme::Light, "light scheme");
    block(
        &mut out,
        ":root[data-scheme=\"dark\"]",
        ColorScheme::Dark,
        "dark scheme — same names, dark values",
    );
    out
}

fn block(out: &mut String, selector: &str, scheme: ColorScheme, comment: &str) {
    let r = roles(scheme);
    let _ = writeln!(out, "{selector} {{ /* {comment} */");
    for (name, value) in color_roles(&r) {
        declare(out, &format!("--micold-{}", kebab(name)), &hex(value));
    }
    type_scale(out);
    corner_radii(out);
    elevations(out, &r, scheme);
    motion(out);
    states(out);
    spacing_scale(out);
    out.push_str("}\n");
}

fn declare(out: &mut String, name: &str, value: &str) {
    let _ = writeln!(out, "  {name}: {value};");
}

/// The identifier *is* the contract: renaming a token in this crate renames the variable, `site.css`
/// stops finding it, and the site build fails. That coupling is the point — the alternative is a
/// site that silently keeps painting last release's colours.
fn kebab(identifier: &str) -> String {
    identifier.replace('_', "-")
}

fn hex(color: Rgb) -> String {
    format!("#{:02x}{:02x}{:02x}", color.r, color.g, color.b)
}

/// Every field of [`Roles`], paired with its own identifier.
///
/// Spelled out rather than derived: a macro over the struct would emit whatever fields happen to
/// exist, so adding a private helper field would silently add a public CSS variable. This list is
/// the emitter's declaration of what the site is allowed to see.
fn color_roles(r: &Roles) -> [(&'static str, Rgb); 36] {
    [
        ("primary", r.primary),
        ("on_primary", r.on_primary),
        ("primary_container", r.primary_container),
        ("on_primary_container", r.on_primary_container),
        ("secondary", r.secondary),
        ("on_secondary", r.on_secondary),
        ("secondary_container", r.secondary_container),
        ("on_secondary_container", r.on_secondary_container),
        ("tertiary", r.tertiary),
        ("on_tertiary", r.on_tertiary),
        ("tertiary_container", r.tertiary_container),
        ("on_tertiary_container", r.on_tertiary_container),
        ("error", r.error),
        ("on_error", r.on_error),
        ("error_container", r.error_container),
        ("on_error_container", r.on_error_container),
        ("background", r.background),
        ("on_background", r.on_background),
        ("surface", r.surface),
        ("on_surface", r.on_surface),
        ("surface_dim", r.surface_dim),
        ("surface_bright", r.surface_bright),
        ("surface_container_lowest", r.surface_container_lowest),
        ("surface_container_low", r.surface_container_low),
        ("surface_container", r.surface_container),
        ("surface_container_high", r.surface_container_high),
        ("surface_container_highest", r.surface_container_highest),
        ("surface_variant", r.surface_variant),
        ("on_surface_variant", r.on_surface_variant),
        ("outline", r.outline),
        ("outline_variant", r.outline_variant),
        ("inverse_surface", r.inverse_surface),
        ("inverse_on_surface", r.inverse_on_surface),
        ("inverse_primary", r.inverse_primary),
        ("scrim", r.scrim),
        ("shadow", r.shadow),
    ]
}

/// Size, line height and weight — but never `tracking`, which the renderer records and does not
/// apply (FR-042). A site that applied it would set its prose at a spacing no screenshot on that
/// same page can show.
fn type_scale(out: &mut String) {
    for role in typography::ALL {
        let base = format!("--micold-type-{}", kebab(role.name));
        declare(out, &format!("{base}-size"), &format!("{}px", role.size));
        declare(
            out,
            &format!("{base}-line-height"),
            &format!("{}px", role.line_height),
        );
        declare(out, &format!("{base}-weight"), &role.weight.to_string());
    }
}

fn corner_radii(out: &mut String) {
    for (name, value) in [
        ("none", shape::NONE),
        ("extra-small", shape::EXTRA_SMALL),
        ("small", shape::SMALL),
        ("medium", shape::MEDIUM),
        ("large", shape::LARGE),
        ("extra-large", shape::EXTRA_LARGE),
        ("full", shape::FULL),
    ] {
        declare(
            out,
            &format!("--micold-shape-corner-{name}"),
            &format!("{value}px"),
        );
    }
}

/// Each level emits **both** of its cues: the complete `box-shadow`, and the tonal surface it
/// resolves to. Carrying only the shadow would lose the level entirely in the dark scheme, where
/// the tone is the primary cue and a black shadow is nearly invisible (`elevation.rs` module docs).
fn elevations(out: &mut String, r: &Roles, scheme: ColorScheme) {
    for level in elevation::LEVELS {
        let shadow = match level.shadow {
            None => "none".to_string(),
            Some(s) => {
                let alpha = match scheme {
                    ColorScheme::Light => s.alpha_light,
                    ColorScheme::Dark => s.alpha_dark,
                };
                format!(
                    "0 {}px {}px rgba({}, {}, {}, {alpha})",
                    s.offset_y, s.blur, r.shadow.r, r.shadow.g, r.shadow.b
                )
            }
        };
        declare(out, &format!("--micold-elevation-{}", level.level), &shadow);
        declare(
            out,
            &format!("--micold-elevation-{}-surface", level.level),
            &hex(r.elevation_surface(level.level)),
        );
    }
    declare(
        out,
        "--micold-scrim-opacity",
        &elevation::SCRIM_ALPHA.to_string(),
    );
}

fn motion(out: &mut String) {
    for (name, value) in [
        ("short-1", motion::duration::SHORT_1),
        ("short-2", motion::duration::SHORT_2),
        ("short-3", motion::duration::SHORT_3),
        ("short-4", motion::duration::SHORT_4),
        ("medium-1", motion::duration::MEDIUM_1),
        ("medium-2", motion::duration::MEDIUM_2),
        ("medium-3", motion::duration::MEDIUM_3),
        ("medium-4", motion::duration::MEDIUM_4),
        ("long-1", motion::duration::LONG_1),
        ("long-2", motion::duration::LONG_2),
        ("long-3", motion::duration::LONG_3),
        ("long-4", motion::duration::LONG_4),
    ] {
        declare(
            out,
            &format!("--micold-motion-duration-{name}"),
            &format!("{value}ms"),
        );
    }
    for (name, e) in [
        ("standard", motion::STANDARD),
        ("standard-accelerate", motion::STANDARD_ACCELERATE),
        ("standard-decelerate", motion::STANDARD_DECELERATE),
        ("emphasized", motion::EMPHASIZED),
        ("emphasized-accelerate", motion::EMPHASIZED_ACCELERATE),
        ("emphasized-decelerate", motion::EMPHASIZED_DECELERATE),
    ] {
        declare(
            out,
            &format!("--micold-motion-easing-{name}"),
            &format!("cubic-bezier({}, {}, {}, {})", e.x1, e.y1, e.x2, e.y2),
        );
    }
}

fn states(out: &mut String) {
    for (name, value) in [
        ("hover", state::HOVER),
        ("focus", state::FOCUS),
        ("pressed", state::PRESSED),
        ("dragged", state::DRAGGED),
        ("selected", state::SELECTED),
        ("disabled-content", state::DISABLED_CONTENT),
        ("disabled-container", state::DISABLED_CONTAINER),
    ] {
        declare(
            out,
            &format!("--micold-state-{name}-opacity"),
            &value.to_string(),
        );
    }
    declare(
        out,
        "--micold-state-focus-ring-width",
        &format!("{}px", state::FOCUS_RING_WIDTH),
    );
}

fn spacing_scale(out: &mut String) {
    for (name, value) in [
        ("xs", spacing::XS),
        ("sm", spacing::SM),
        ("md", spacing::MD),
        ("lg", spacing::LG),
        ("xl", spacing::XL),
    ] {
        declare(out, &format!("--micold-spacing-{name}"), &format!("{value}px"));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::BTreeMap;

    /// The declarations of one `:root` block, as name → value, in source order.
    fn block(scheme: &str) -> BTreeMap<String, String> {
        let sheet = stylesheet();
        let opener = match scheme {
            "light" => ":root {",
            "dark" => ":root[data-scheme=\"dark\"] {",
            other => panic!("no such block: {other}"),
        };
        let start = sheet
            .find(opener)
            .unwrap_or_else(|| panic!("the emitted sheet has no `{opener}` block"))
            + opener.len();
        let end = start
            + sheet[start..]
                .find('}')
                .expect("the block is never closed");
        let mut out = BTreeMap::new();
        for line in sheet[start..end].lines() {
            let line = line.trim();
            let Some((name, value)) = line.split_once(':') else {
                continue;
            };
            if !name.starts_with("--micold-") {
                continue;
            }
            out.insert(
                name.trim().to_string(),
                value.trim().trim_end_matches(';').trim().to_string(),
            );
        }
        out
    }

    fn kebab(identifier: &str) -> String {
        identifier.replace('_', "-")
    }

    const COLOR_ROLES: [&str; 36] = [
        "primary",
        "on_primary",
        "primary_container",
        "on_primary_container",
        "secondary",
        "on_secondary",
        "secondary_container",
        "on_secondary_container",
        "tertiary",
        "on_tertiary",
        "tertiary_container",
        "on_tertiary_container",
        "error",
        "on_error",
        "error_container",
        "on_error_container",
        "background",
        "on_background",
        "surface",
        "on_surface",
        "surface_dim",
        "surface_bright",
        "surface_container_lowest",
        "surface_container_low",
        "surface_container",
        "surface_container_high",
        "surface_container_highest",
        "surface_variant",
        "on_surface_variant",
        "outline",
        "outline_variant",
        "inverse_surface",
        "inverse_on_surface",
        "inverse_primary",
        "scrim",
        "shadow",
    ];

    /// A name defined in one block and missing from the other is the derivation failing silently:
    /// the variable falls back to its initial value and the page renders in something that is not
    /// the application's palette at all.
    #[test]
    fn every_name_is_defined_in_both_schemes() {
        let light = block("light");
        let dark = block("dark");
        assert!(!light.is_empty(), "the light block emitted no declarations");
        let only_light: Vec<_> = light.keys().filter(|k| !dark.contains_key(*k)).collect();
        let only_dark: Vec<_> = dark.keys().filter(|k| !light.contains_key(*k)).collect();
        assert!(
            only_light.is_empty() && only_dark.is_empty(),
            "light-only: {only_light:?}; dark-only: {only_dark:?}"
        );
    }

    #[test]
    fn every_colour_role_is_emitted_as_a_hex_triple() {
        for scheme in ["light", "dark"] {
            let declarations = block(scheme);
            for role in COLOR_ROLES {
                let name = format!("--micold-{}", kebab(role));
                let value = declarations
                    .get(&name)
                    .unwrap_or_else(|| panic!("{scheme}: {name} is not emitted"));
                assert!(
                    value.len() == 7
                        && value.starts_with('#')
                        && value[1..].chars().all(|c| c.is_ascii_hexdigit()),
                    "{scheme}: {name} is {value}, not #rrggbb"
                );
            }
        }
    }

    #[test]
    fn the_two_schemes_carry_different_values() {
        assert_ne!(
            block("light").get("--micold-surface"),
            block("dark").get("--micold-surface"),
            "both blocks carry the light palette"
        );
    }

    #[test]
    fn the_whole_type_scale_is_emitted_with_units() {
        let declarations = block("light");
        for role in typography::ALL {
            let base = format!("--micold-type-{}", kebab(role.name));
            for (suffix, expected) in [
                ("size", format!("{}px", role.size)),
                ("line-height", format!("{}px", role.line_height)),
                ("weight", role.weight.to_string()),
            ] {
                let name = format!("{base}-{suffix}");
                assert_eq!(
                    declarations.get(&name).map(String::as_str),
                    Some(expected.as_str()),
                    "{name} is not emitted as {expected}"
                );
            }
        }
    }

    /// FR-042: the renderer records tracking and never applies it. A site that applied it would set
    /// its text at a spacing no screenshot on the site can show.
    #[test]
    fn tracking_is_not_emitted() {
        let offenders: Vec<_> = block("light")
            .into_keys()
            .filter(|k| k.ends_with("-tracking"))
            .collect();
        assert!(offenders.is_empty(), "tracking emitted: {offenders:?}");
    }

    #[test]
    fn every_corner_radius_is_emitted_in_px() {
        let declarations = block("light");
        for (name, value) in [
            ("none", shape::NONE),
            ("extra-small", shape::EXTRA_SMALL),
            ("small", shape::SMALL),
            ("medium", shape::MEDIUM),
            ("large", shape::LARGE),
            ("extra-large", shape::EXTRA_LARGE),
            ("full", shape::FULL),
        ] {
            let name = format!("--micold-shape-corner-{name}");
            assert_eq!(
                declarations.get(&name).map(String::as_str),
                Some(format!("{value}px").as_str()),
                "{name} is not emitted as {value}px"
            );
        }
    }

    /// Each level carries both of its cues — the tonal surface and the shadow — because a level
    /// defined by its shadow alone disappears in the dark scheme (`elevation.rs` module docs).
    #[test]
    fn every_elevation_level_carries_a_shadow_and_a_surface() {
        for scheme in ["light", "dark"] {
            let declarations = block(scheme);
            for level in elevation::LEVELS {
                let shadow = format!("--micold-elevation-{}", level.level);
                let value = declarations
                    .get(&shadow)
                    .unwrap_or_else(|| panic!("{scheme}: {shadow} is not emitted"));
                match level.shadow {
                    None => assert_eq!(value, "none", "{scheme}: {shadow} at rest is not `none`"),
                    Some(s) => {
                        assert!(
                            value.contains(&format!("{}px", s.offset_y))
                                && value.contains(&format!("{}px", s.blur))
                                && value.contains("rgba("),
                            "{scheme}: {shadow} is {value}, not a complete box-shadow"
                        );
                    }
                }
                let surface = format!("--micold-elevation-{}-surface", level.level);
                let value = declarations
                    .get(&surface)
                    .unwrap_or_else(|| panic!("{scheme}: {surface} is not emitted"));
                assert!(value.starts_with('#'), "{scheme}: {surface} is {value}");
            }
            assert_eq!(
                declarations
                    .get("--micold-scrim-opacity")
                    .map(String::as_str),
                Some(elevation::SCRIM_ALPHA.to_string().as_str()),
            );
        }
    }

    #[test]
    fn every_duration_and_easing_is_emitted_complete() {
        let declarations = block("light");
        for (name, value) in [
            ("short-1", motion::duration::SHORT_1),
            ("short-2", motion::duration::SHORT_2),
            ("short-3", motion::duration::SHORT_3),
            ("short-4", motion::duration::SHORT_4),
            ("medium-1", motion::duration::MEDIUM_1),
            ("medium-2", motion::duration::MEDIUM_2),
            ("medium-3", motion::duration::MEDIUM_3),
            ("medium-4", motion::duration::MEDIUM_4),
            ("long-1", motion::duration::LONG_1),
            ("long-2", motion::duration::LONG_2),
            ("long-3", motion::duration::LONG_3),
            ("long-4", motion::duration::LONG_4),
        ] {
            let name = format!("--micold-motion-duration-{name}");
            assert_eq!(
                declarations.get(&name).map(String::as_str),
                Some(format!("{value}ms").as_str()),
                "{name} is not emitted as {value}ms"
            );
        }
        for (name, easing) in [
            ("standard", motion::STANDARD),
            ("standard-accelerate", motion::STANDARD_ACCELERATE),
            ("standard-decelerate", motion::STANDARD_DECELERATE),
            ("emphasized", motion::EMPHASIZED),
            ("emphasized-accelerate", motion::EMPHASIZED_ACCELERATE),
            ("emphasized-decelerate", motion::EMPHASIZED_DECELERATE),
        ] {
            let name = format!("--micold-motion-easing-{name}");
            let expected = format!(
                "cubic-bezier({}, {}, {}, {})",
                easing.x1, easing.y1, easing.x2, easing.y2
            );
            assert_eq!(
                declarations.get(&name).map(String::as_str),
                Some(expected.as_str()),
                "{name} is not emitted as a complete cubic-bezier"
            );
        }
    }

    #[test]
    fn every_state_layer_and_the_focus_ring_are_emitted() {
        let declarations = block("light");
        for (name, value) in [
            ("hover", state::HOVER),
            ("focus", state::FOCUS),
            ("pressed", state::PRESSED),
            ("dragged", state::DRAGGED),
            ("selected", state::SELECTED),
            ("disabled-content", state::DISABLED_CONTENT),
            ("disabled-container", state::DISABLED_CONTAINER),
        ] {
            let name = format!("--micold-state-{name}-opacity");
            assert_eq!(
                declarations.get(&name).map(String::as_str),
                Some(value.to_string().as_str()),
                "{name} is not emitted as {value}"
            );
        }
        assert_eq!(
            declarations
                .get("--micold-state-focus-ring-width")
                .map(String::as_str),
            Some(format!("{}px", state::FOCUS_RING_WIDTH).as_str()),
        );
    }

    #[test]
    fn the_spacing_scale_is_emitted_in_px() {
        let declarations = block("light");
        for (name, value) in [
            ("xs", spacing::XS),
            ("sm", spacing::SM),
            ("md", spacing::MD),
            ("lg", spacing::LG),
            ("xl", spacing::XL),
        ] {
            let name = format!("--micold-spacing-{name}");
            assert_eq!(
                declarations.get(&name).map(String::as_str),
                Some(format!("{value}px").as_str()),
                "{name} is not emitted as {value}px"
            );
        }
    }

    /// The sheet is a build product checked into nothing. Saying so in the file itself is the only
    /// warning a reader who opens it in an editor will get.
    #[test]
    fn the_sheet_says_it_is_generated() {
        let sheet = stylesheet();
        let first = sheet.lines().next().unwrap_or_default();
        assert!(
            first.contains("GENERATED") && first.contains("micold-tokens-css"),
            "the first line is {first:?}"
        );
    }
}
