//! The Material 3 baseline tonal ramps (feature 018, T000f/T000g — FR-001, FR-005a, FR-005b, D1, D3).
//!
//! Every colour role is a **palette + tone** pair rather than an independently chosen hex value
//! (contract §1.1). This module is the palette half: six key ramps derived from Material's own
//! baseline seed `#6750A4`, plus one ramp per worktree tag hue.
//!
//! Both schemes read these same ramps at different tones, so light and dark are structurally locked
//! together: a role added once is correct in both, and its contrast follows from the tone delta
//! rather than from hand-tuning (D3).
//!
//! # Where these numbers came from
//!
//! Generated by a port of Google's `material-color-utilities` HCT solver (CAM16 hue/chroma with
//! CIELAB tone, and the analytic gamut-boundary solve), then checked in as data — the contract
//! forbids a build-time generation step or any runtime colour science (§1.1).
//!
//! The port was validated before its output was trusted, because a plausible-but-wrong ramp is
//! invisible: every colour still *looks* like a colour.
//!
//! - Against `material-color-utilities`' own published test data: the blue palette of
//!   `typescript/palettes/palettes_test.ts` reproduces **12 of 12** tones exactly.
//! - Against the baseline scheme's error roles in
//!   `swift/Tests/.../SchemeTests/SchemeTonalSpotTests.swift`.
//! - [`PRIMARY`] tone 40 round-trips the seed itself, which is the strongest available check that
//!   these ramps belong to the scheme they claim to. `tests/tokens_contrast.rs` asserts it.
//!
//! **One value is pinned rather than generated.** `ERROR` tone 40 is the published `#BA1A1A`; the
//! port produces `#BA1B1B`, one bit apart in two channels, from the last round of a five-step
//! Newton solve. `error` is a role a user looks at and the reference is authoritative, so the
//! published value wins. `tests/tokens_contrast.rs` pins all four published error tones so this
//! cannot silently drift.

use super::Rgb;

/// The Material tone stops. Normative (contract §1.1); `tests/tokens_contrast.rs` asserts the list.
pub const TONES: [u8; 23] = [
    0, 4, 6, 10, 12, 17, 20, 22, 24, 30, 40, 50, 60, 70, 80, 87, 90, 92, 94, 95, 96, 98, 100,
];

/// One key palette: the same hue and chroma sampled at each of [`TONES`].
///
/// Tone is perceptual lightness, so a ramp is monotonically lighter as tone rises — a property
/// `tests/tokens_contrast.rs` asserts, because it is what catches a transcription slip that
/// contrast assertions would let through.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Ramp([Rgb; TONES.len()]);

impl Ramp {
    /// The colour at a Material tone stop.
    ///
    /// Panics on a tone that is not one of [`TONES`]. Deliberate, and safe: every call site is a
    /// `const` in this crate reading a tone the contract names, so an invalid tone is a compile-time
    /// failure rather than something a user can reach.
    pub const fn at(&self, tone: u8) -> Rgb {
        let mut i = 0;
        while i < TONES.len() {
            if TONES[i] == tone {
                return self.0[i];
            }
            i += 1;
        }
        panic!("not a Material tone stop — see tokens::palette::TONES")
    }
}

/// A worktree tag's hue, at the four tones the tag recipe uses (contract §1.4): fill 40 / text 100
/// in light, fill 80 / text 20 in dark.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct TagRamp([Rgb; 4]);

impl TagRamp {
    /// The colour at tone 20, 40, 80 or 100. Panics on any other tone, for the same reason as
    /// [`Ramp::at`].
    pub const fn at(&self, tone: u8) -> Rgb {
        match tone {
            20 => self.0[0],
            40 => self.0[1],
            80 => self.0[2],
            100 => self.0[3],
            _ => panic!("a tag ramp carries only tones 20, 40, 80 and 100"),
        }
    }
}

// --- the six key ramps, from seed #6750A4 ------------------------------------------------------

pub const PRIMARY: Ramp = Ramp([
    Rgb::hex(0x000000), // 0
    Rgb::hex(0x13003A), // 4
    Rgb::hex(0x190048), // 6
    Rgb::hex(0x22005D), // 10
    Rgb::hex(0x260561), // 12
    Rgb::hex(0x31166C), // 17
    Rgb::hex(0x381E72), // 20
    Rgb::hex(0x3C2377), // 22
    Rgb::hex(0x41287C), // 24
    Rgb::hex(0x4F378A), // 30
    Rgb::hex(0x6750A4), // 40  <- the seed
    Rgb::hex(0x8069BF), // 50
    Rgb::hex(0x9A83DB), // 60
    Rgb::hex(0xB69DF8), // 70
    Rgb::hex(0xCFBCFF), // 80
    Rgb::hex(0xE1D3FF), // 87
    Rgb::hex(0xE9DDFF), // 90
    Rgb::hex(0xEEE4FF), // 92
    Rgb::hex(0xF3EAFF), // 94
    Rgb::hex(0xF6EEFF), // 95
    Rgb::hex(0xF8F1FF), // 96
    Rgb::hex(0xFDF7FF), // 98
    Rgb::hex(0xFFFFFF), // 100
]);

pub const SECONDARY: Ramp = Ramp([
    Rgb::hex(0x000000), // 0
    Rgb::hex(0x100B1D), // 4
    Rgb::hex(0x151022), // 6
    Rgb::hex(0x1E192B), // 10
    Rgb::hex(0x221D2F), // 12
    Rgb::hex(0x2C273A), // 17
    Rgb::hex(0x332D41), // 20
    Rgb::hex(0x373245), // 22
    Rgb::hex(0x3C364A), // 24
    Rgb::hex(0x4A4458), // 30
    Rgb::hex(0x625B71), // 40
    Rgb::hex(0x7B748A), // 50
    Rgb::hex(0x958DA4), // 60
    Rgb::hex(0xB0A7C0), // 70
    Rgb::hex(0xCCC2DB), // 80
    Rgb::hex(0xE0D6F0), // 87
    Rgb::hex(0xE8DEF8), // 90
    Rgb::hex(0xEEE4FE), // 92
    Rgb::hex(0xF3EAFF), // 94
    Rgb::hex(0xF6EEFF), // 95
    Rgb::hex(0xF8F1FF), // 96
    Rgb::hex(0xFDF7FF), // 98
    Rgb::hex(0xFFFFFF), // 100
]);

pub const TERTIARY: Ramp = Ramp([
    Rgb::hex(0x000000), // 0
    Rgb::hex(0x210410), // 4
    Rgb::hex(0x270815), // 6
    Rgb::hex(0x31101D), // 10
    Rgb::hex(0x361421), // 12
    Rgb::hex(0x421F2C), // 17
    Rgb::hex(0x4A2532), // 20
    Rgb::hex(0x4F2936), // 22
    Rgb::hex(0x542E3B), // 24
    Rgb::hex(0x633B48), // 30
    Rgb::hex(0x7E5260), // 40
    Rgb::hex(0x996A79), // 50
    Rgb::hex(0xB58392), // 60
    Rgb::hex(0xD29DAD), // 70
    Rgb::hex(0xEFB8C8), // 80
    Rgb::hex(0xFFCDDB), // 87
    Rgb::hex(0xFFD9E3), // 90
    Rgb::hex(0xFFE1E8), // 92
    Rgb::hex(0xFFE8ED), // 94
    Rgb::hex(0xFFECF0), // 95
    Rgb::hex(0xFFF0F2), // 96
    Rgb::hex(0xFFF8F8), // 98
    Rgb::hex(0xFFFFFF), // 100
]);

pub const ERROR: Ramp = Ramp([
    Rgb::hex(0x000000), // 0
    Rgb::hex(0x280001), // 4
    Rgb::hex(0x310001), // 6
    Rgb::hex(0x410002), // 10
    Rgb::hex(0x490002), // 12
    Rgb::hex(0x5C0004), // 17
    Rgb::hex(0x690005), // 20
    Rgb::hex(0x710005), // 22
    Rgb::hex(0x790006), // 24
    Rgb::hex(0x93000A), // 30  <- published
    Rgb::hex(0xBA1A1A), // 40  <- published (pinned; the generator gives #BA1B1B)
    Rgb::hex(0xDE3730), // 50
    Rgb::hex(0xFF5449), // 60
    Rgb::hex(0xFF897D), // 70
    Rgb::hex(0xFFB4AB), // 80  <- published
    Rgb::hex(0xFFCFC9), // 87
    Rgb::hex(0xFFDAD6), // 90  <- published
    Rgb::hex(0xFFE2DE), // 92
    Rgb::hex(0xFFE9E6), // 94
    Rgb::hex(0xFFEDEA), // 95
    Rgb::hex(0xFFF0EE), // 96
    Rgb::hex(0xFFF8F7), // 98
    Rgb::hex(0xFFFFFF), // 100
]);

pub const NEUTRAL: Ramp = Ramp([
    Rgb::hex(0x000000), // 0
    Rgb::hex(0x0F0E11), // 4
    Rgb::hex(0x141316), // 6
    Rgb::hex(0x1C1B1E), // 10
    Rgb::hex(0x201F22), // 12
    Rgb::hex(0x2B292D), // 17
    Rgb::hex(0x313033), // 20
    Rgb::hex(0x363438), // 22
    Rgb::hex(0x3A383C), // 24
    Rgb::hex(0x48464A), // 30
    Rgb::hex(0x605D62), // 40
    Rgb::hex(0x79767A), // 50
    Rgb::hex(0x938F94), // 60
    Rgb::hex(0xAEAAAE), // 70
    Rgb::hex(0xCAC5CA), // 80
    Rgb::hex(0xDDD8DD), // 87
    Rgb::hex(0xE6E1E6), // 90
    Rgb::hex(0xECE7EC), // 92
    Rgb::hex(0xF2ECF1), // 94
    Rgb::hex(0xF5EFF4), // 95
    Rgb::hex(0xF8F2F7), // 96
    Rgb::hex(0xFDF8FD), // 98
    Rgb::hex(0xFFFFFF), // 100
]);

pub const NEUTRAL_VARIANT: Ramp = Ramp([
    Rgb::hex(0x000000), // 0
    Rgb::hex(0x0F0D14), // 4
    Rgb::hex(0x14121A), // 6
    Rgb::hex(0x1D1A22), // 10
    Rgb::hex(0x211E26), // 12
    Rgb::hex(0x2B2931), // 17
    Rgb::hex(0x322F38), // 20
    Rgb::hex(0x36333C), // 22
    Rgb::hex(0x3B3840), // 24
    Rgb::hex(0x49454E), // 30
    Rgb::hex(0x615D66), // 40
    Rgb::hex(0x7A757F), // 50
    Rgb::hex(0x948F99), // 60
    Rgb::hex(0xAFA9B4), // 70
    Rgb::hex(0xCAC4CF), // 80
    Rgb::hex(0xDED8E3), // 87
    Rgb::hex(0xE7E0EC), // 90
    Rgb::hex(0xEDE6F1), // 92
    Rgb::hex(0xF2ECF7), // 94
    Rgb::hex(0xF5EEFA), // 95
    Rgb::hex(0xF8F1FD), // 96
    Rgb::hex(0xFDF7FF), // 98
    Rgb::hex(0xFFFFFF), // 100
]);

// --- tag hues (contract §1.4) ------------------------------------------------------------------
//
// One fixed hue per conventional-commit type. The contract names the colour, not the angle, so the
// angles are chosen here: spread so no two adjacent types collide, and kept clear of the primary
// palette's hue so `refactor`'s deep purple stays distinguishable from the accent, as §1.4 requires.
//
// Each is read at the same tone recipe as the accent roles — fill 40 / text 100 in light, fill 80 /
// text 20 in dark — so AA holds by construction rather than by 10 x 2 x 3 hand-checks.

/// green
pub const TAG_FEAT: TagRamp = TagRamp([
    Rgb::hex(0x013A00),
    Rgb::hex(0x306B25),
    Rgb::hex(0x96D783),
    Rgb::hex(0xFFFFFF),
]);
/// red
pub const TAG_FIX: TagRamp = TagRamp([
    Rgb::hex(0x5F150D),
    Rgb::hex(0x9C4236),
    Rgb::hex(0xFFB4A8),
    Rgb::hex(0xFFFFFF),
]);
/// brown
pub const TAG_CHORE: TagRamp = TagRamp([
    Rgb::hex(0x492900),
    Rgb::hex(0x8A5100),
    Rgb::hex(0xFFB86E),
    Rgb::hex(0xFFFFFF),
]);
/// teal
pub const TAG_DOCS: TagRamp = TagRamp([
    Rgb::hex(0x003736),
    Rgb::hex(0x006A68),
    Rgb::hex(0x4DDAD7),
    Rgb::hex(0xFFFFFF),
]);
/// deep purple
pub const TAG_REFACTOR: TagRamp = TagRamp([
    Rgb::hex(0x431A6B),
    Rgb::hex(0x744C9D),
    Rgb::hex(0xDCB8FF),
    Rgb::hex(0xFFFFFF),
]);
/// blue
pub const TAG_TEST: TagRamp = TagRamp([
    Rgb::hex(0x00315D),
    Rgb::hex(0x1A60A5),
    Rgb::hex(0xA4C9FF),
    Rgb::hex(0xFFFFFF),
]);
/// orange
pub const TAG_BUILD: TagRamp = TagRamp([
    Rgb::hex(0x452B00),
    Rgb::hex(0x825500),
    Rgb::hex(0xFFB94E),
    Rgb::hex(0xFFFFFF),
]);
/// indigo
pub const TAG_CI: TagRamp = TagRamp([
    Rgb::hex(0x0B2878),
    Rgb::hex(0x4359A9),
    Rgb::hex(0xB7C4FF),
    Rgb::hex(0xFFFFFF),
]);
/// pink
pub const TAG_PERF: TagRamp = TagRamp([
    Rgb::hex(0x5D1139),
    Rgb::hex(0x964168),
    Rgb::hex(0xFFB0CF),
    Rgb::hex(0xFFFFFF),
]);
/// lime
pub const TAG_STYLE: TagRamp = TagRamp([
    Rgb::hex(0x2D3400),
    Rgb::hex(0x596400),
    Rgb::hex(0xC0CF5F),
    Rgb::hex(0xFFFFFF),
]);
/// neutral — the issue tag, deliberately without a hue of its own (FR-006a)
pub const TAG_ISSUE: TagRamp = TagRamp([
    Rgb::hex(0x352F30),
    Rgb::hex(0x645C5E),
    Rgb::hex(0xCFC4C5),
    Rgb::hex(0xFFFFFF),
]);
