#!/usr/bin/env bash
# A private X display for the capture run (feature 028, T018).
#
# Every screenshot on the published site is of a real window, which means something has to draw one.
# The obvious way -- use whatever display is already there -- is wrong in both directions:
#
#   * On a developer's machine it captures *their* desktop. Their wallpaper, their other windows,
#     their GTK theme and their cursor end up in the published PNG, and the result is different for
#     every person who runs it. `scripts/tests/capture-harness.test.sh` exists because that failure
#     looks perfectly fine to whoever produced it.
#   * On a CI runner there is no display at all, so nothing draws and the run fails late.
#
# So the run owns its display: a private `Xvfb` at a display number nobody else holds, with its own
# `XDG_RUNTIME_DIR`, `XDG_DATA_HOME`, `XDG_CONFIG_HOME` and `XDG_CACHE_HOME`, and with
# `WAYLAND_DISPLAY` cleared so the toolkit cannot quietly prefer the host's real session over the
# display we just made (FR-011b).
#
# Rendering is Mesa's `lavapipe`: the client is a wgpu application, CI runners have no GPU, and a
# capture that only works where there is a GPU is a capture that does not work.
#
#   eval "$(site/capture/display.sh start)"   # no: `start` prints a *file*, not shell
#   . "$(site/capture/display.sh start)"      # yes -- source the env file it names
#   site/capture/display.sh stop
#
# `start` prints the path of a file of `export` lines on stdout, and everything else on stderr, so
# it composes. It is idempotent: a second `start` prints the same file for the display already up.

set -euo pipefail

root="$(git rev-parse --show-toplevel)"

# One state directory per checkout per user, at a *short* path. Short matters: the display's
# sockets live under `XDG_RUNTIME_DIR`, and an AF_UNIX path is limited to about 100 characters --
# a worktree path under a deep home directory would silently exceed it. Per-checkout matters
# because two agents working in two worktrees must not land on one another's display.
key="$(printf '%s' "$root" | cksum | cut -d' ' -f1)"
state="${MICOLD_CAPTURE_STATE:-/tmp/micold-cap-$(id -u)-$key}"
env_file="$state/env"
pid_file="$state/xvfb.pid"

# 1600x1000 is a laptop-shaped viewport with room for the window chrome the scenes place inside it.
# The scenes size the *window* themselves; this is only the desk it sits on.
geometry="${MICOLD_CAPTURE_GEOMETRY:-1600x1000x24}"

die() {
  printf 'display.sh: %s\n' "$1" >&2
  exit 1
}

running() {
  [ -f "$pid_file" ] && kill -0 "$(cat "$pid_file")" 2>/dev/null
}

start() {
  if running; then
    [ -f "$env_file" ] || die "$pid_file names a live process but $env_file is gone"
    printf '%s\n' "$env_file"
    return 0
  fi

  command -v Xvfb >/dev/null 2>&1 || die "Xvfb is not installed (see site/README.md)"
  command -v xdotool >/dev/null 2>&1 || die "xdotool is not installed (see site/README.md)"

  rm -rf "$state"
  mkdir -p "$state/run" "$state/data" "$state/config" "$state/cache"
  chmod 700 "$state/run"

  # Display numbers are a shared namespace on this machine, so the number is *found*, not assumed:
  # `-displayfd` would be the tidy way, but it is easier to reason about a run whose display number
  # is stable across a session, and the lock file tells us what is taken.
  local n display=""
  for n in $(seq 90 119); do
    if [ ! -e "/tmp/.X$n-lock" ] && [ ! -e "/tmp/.X11-unix/X$n" ]; then
      display=":$n"
      break
    fi
  done
  [ -n "$display" ] || die "no free X display number between :90 and :119"

  Xvfb "$display" -screen 0 "$geometry" -nolisten tcp -noreset >"$state/xvfb.log" 2>&1 &
  echo $! >"$pid_file"

  # Wait for the server to actually answer. Starting Xvfb and immediately launching the client is
  # the classic way to get an intermittent "cannot open display" on a loaded machine.
  local waited=0
  until DISPLAY="$display" xdotool getdisplaygeometry >/dev/null 2>&1; do
    waited=$((waited + 1))
    if [ "$waited" -gt 100 ]; then
      kill "$(cat "$pid_file")" 2>/dev/null || true
      die "$display did not come up in 10s: $(tail -3 "$state/xvfb.log")"
    fi
    sleep 0.1
  done

  # `unset WAYLAND_DISPLAY` rather than setting it empty: some toolkits treat "set but empty" as a
  # request to use the default Wayland socket, which is exactly the host session we are avoiding.
  cat >"$env_file" <<ENV
# GENERATED by site/capture/display.sh. Source this; do not edit.
export DISPLAY=$display
export MICOLD_CAPTURE_DISPLAY=$display
export XDG_RUNTIME_DIR=$state/run
export XDG_DATA_HOME=$state/data
export XDG_CONFIG_HOME=$state/config
export XDG_CACHE_HOME=$state/cache
unset WAYLAND_DISPLAY
# Software rendering: no CI runner has a GPU, and a capture that needs one is not reproducible.
export WGPU_BACKEND=vulkan
export VK_ICD_FILENAMES=${MICOLD_CAPTURE_ICD:-/usr/share/vulkan/icd.d/lvp_icd.json}
export LIBGL_ALWAYS_SOFTWARE=1
export GDK_BACKEND=x11
export WINIT_UNIX_BACKEND=x11
ENV

  printf 'display.sh: %s is up (%s), state in %s\n' "$display" "$geometry" "$state" >&2
  printf '%s\n' "$env_file"
}

stop() {
  if running; then
    local pid
    pid="$(cat "$pid_file")"
    kill "$pid" 2>/dev/null || true
    local waited=0
    while kill -0 "$pid" 2>/dev/null && [ "$waited" -lt 50 ]; do
      waited=$((waited + 1))
      sleep 0.1
    done
    kill -9 "$pid" 2>/dev/null || true
  fi
  rm -rf "$state"
}

case "${1:-}" in
  start) start ;;
  stop) stop ;;
  status) running && printf 'up\n' || { printf 'down\n'; exit 1; } ;;
  -h | --help | "") sed -n '2,27p' "$0"; exit 0 ;;
  *) die "unknown command: $1 (start | stop | status)" ;;
esac
