//! Protocol version + schema hash (contracts/protocol.md §4).
//!
//! [`PROTOCOL_VERSION`] is the human-facing number, bumped on any wire-visible change.
//! [`SCHEMA_HASH`] is generated by `build.rs` over the canonical text of `messages.rs`, `grid.rs`
//! and `envelope.rs` — it catches the case the integer cannot: a message struct edited without a
//! version bump. Because both binaries compile the same `micold-core`, two builds that disagree
//! about the wire necessarily disagree on the hash, and the handshake refuses them. Strictly
//! stricter than the version check, never a substitute for it.

/// The wire protocol version. MUST be bumped on any wire-visible change.
///
/// Bumped 1 → 2 for `ClientMsg::Hello::client_package_version` (FR-022a, BUG-002).
/// Bumped 2 → 3 for `SessionSummary::input_serial` (FR-028a, BUG-006).
/// Bumped 3 → 4 for `OperationResult::WorktreeDeleted::leftovers` (FR-023).
/// Bumped 4 → 5 for `DaemonMsg::OperationProgress::detail` (FR-004a, BUG-009).
pub const PROTOCOL_VERSION: u32 = 5;

// `build.rs` emits `pub const SCHEMA_HASH: [u8; 32] = [...];` into this file.
include!(concat!(env!("OUT_DIR"), "/schema_hash.rs"));

/// This build's package version (`CARGO_PKG_VERSION` of *this* crate). Every workspace member
/// shares one version (`version.workspace = true`), so this is also the daemon's and the client's
/// own package version, each frozen into its own compiled binary — the same way `PROTOCOL_VERSION`
/// and `SCHEMA_HASH` are. Unlike them, it changes on **every** release, wire-visible or not, which
/// is exactly the granularity FR-022a needs: detecting that the on-disk `.deb` shipped a newer
/// daemon than the one still running, independent of whether the wire contract moved (FR-022a,
/// BUG-002).
pub const PACKAGE_VERSION: &str = env!("CARGO_PKG_VERSION");
