//! Protocol version + schema hash (contracts/protocol.md §4).
//!
//! [`PROTOCOL_VERSION`] is the human-facing number, bumped on any wire-visible change.
//! [`SCHEMA_HASH`] is generated by `build.rs` over the canonical text of `messages.rs`, `grid.rs`
//! and `envelope.rs` — it catches the case the integer cannot: a message struct edited without a
//! version bump. Because both binaries compile the same `micold-core`, two builds that disagree
//! about the wire necessarily disagree on the hash, and the handshake refuses them. Strictly
//! stricter than the version check, never a substitute for it.

/// The wire protocol version. MUST be bumped on any wire-visible change.
pub const PROTOCOL_VERSION: u32 = 1;

// `build.rs` emits `pub const SCHEMA_HASH: [u8; 32] = [...];` into this file.
include!(concat!(env!("OUT_DIR"), "/schema_hash.rs"));
