//! Protocol version + schema hash (contracts/protocol.md §4).
//!
//! [`PROTOCOL_VERSION`] is the human-facing number, bumped on any wire-visible change.
//! [`SCHEMA_HASH`] is generated by `build.rs` over the canonical text of `messages.rs`, `grid.rs`
//! and `envelope.rs` — it catches the case the integer cannot: a message struct edited without a
//! version bump. Because both binaries compile the same `micold-core`, two builds that disagree
//! about the wire necessarily disagree on the hash, and the handshake refuses them. Strictly
//! stricter than the version check, never a substitute for it.

/// The wire protocol version. MUST be bumped on any wire-visible change.
///
/// Bumped 1 → 2 for `ClientMsg::Hello::client_package_version` (FR-022a, BUG-002).
/// Bumped 2 → 3 for `SessionSummary::input_serial` (FR-028a, BUG-006).
/// Bumped 3 → 4 for `OperationResult::WorktreeDeleted::leftovers` (FR-023).
/// Bumped 4 → 5 for `DaemonMsg::OperationProgress::detail` (FR-004a, BUG-009).
/// Bumped 5 → 6 for `SessionSummary::live_shells` (`012` FR-008, BUG-003).
/// Bumped 6 → 7 for feature 026's five additions, made together in one edit so the hash moves
/// **once** for the whole feature: `provider` on `ClientMsg::SessionCreate` (inbound) and on
/// `SessionSummary` (outbound), and `default_ai_cli` on `DaemonSettings`, `SettingsSet` and
/// `SettingsChanged`. A second bump later in the feature would fail `tests/schema_hash.rs`.
/// Bumped 7 → 8 for feature 027, in one edit for the same reason 026 used one: the sandbox
/// handshake gives `ClientMsg::Hello` an authentication token and a build fingerprint — together,
/// because the sandbox transport is loopback TCP, which unlike the `0700`-guarded socket
/// authenticates nobody (research R1/R8) — and `ClientMsg::RepoRootQuery` /
/// `OperationResult::RepoRoot` let the open-project gate be answered by the side that will
/// actually run git, which is the only side that can where the client cannot see the daemon's
/// filesystem at the same paths: Windows, and the remote placement (research R2).
///
/// 027 developed against 6 and 7 of its own while 026 was taking the same two numbers on main.
/// Both wire changes are present here, so both cannot be 7; the feature's whole delta is 8.
/// Bumped 8 → 9 for `010` BUG-022, in one edit for the reason 026 and 027 each used one: a client
/// *window* becomes nameable on the wire. `ClientMsg::Hello` gains `client_instance`, and the two
/// frames that report who holds a project — `DaemonMsg::Displaced::by` and
/// `RefusalReason::ProjectBusy::holder` — carry a `ClientIdentity` (build **and** instance) where
/// they carried a build string. All three are the same change: without the instance on the way in
/// the daemon has none to report back, and without it on the way out a window cannot tell another
/// window's takeover from its own reconnect displacing its own dead connection. It also settles
/// BUG-023's deferred half, the holder that named nothing.
pub const PROTOCOL_VERSION: u32 = 9;

// `build.rs` emits `pub const SCHEMA_HASH: [u8; 32] = [...];` into this file.
include!(concat!(env!("OUT_DIR"), "/schema_hash.rs"));

// `build.rs` emits `BUILD_FINGERPRINT` — a value that changes on every build of this crate's
// sources, not every release — into this file, carrying its own doc comment (the one above cannot
// live here, because rustdoc does not document a macro invocation).
//
// The three constants above cannot detect a stale development image: within one released version, a
// daemon rebuilt yesterday and a client built today present identical values for all of them, so the
// handshake accepts a `:dev` image that is behind the tree and the daemon then misbehaves in ways
// that look like bugs in the new code (feature 027, FR-024d, research R8). The comparison is
// deliberately asymmetric — see `sandbox::image::ImageSource::refuses_fingerprint_mismatch`.
include!(concat!(env!("OUT_DIR"), "/build_fingerprint.rs"));

/// This build's package version (`CARGO_PKG_VERSION` of *this* crate). Every workspace member
/// shares one version (`version.workspace = true`), so this is also the daemon's and the client's
/// own package version, each frozen into its own compiled binary — the same way `PROTOCOL_VERSION`
/// and `SCHEMA_HASH` are. Unlike them, it changes on **every** release, wire-visible or not, which
/// is exactly the granularity FR-022a needs: detecting that the on-disk `.deb` shipped a newer
/// daemon than the one still running, independent of whether the wire contract moved (FR-022a,
/// BUG-002).
pub const PACKAGE_VERSION: &str = env!("CARGO_PKG_VERSION");
